apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"lb-svc","namespace":"default"},"spec":{"ports":[{"name":"poc","port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app.oam.dev/component":"wordpress"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-12-05T10:21:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.oam.dev/component: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-12-05T10:21:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: cloud-controller-manager
    operation: Update
    time: "2020-12-05T10:21:55Z"
  name: lb-svc
  namespace: default
  resourceVersion: "19357467"
  selfLink: /api/v1/namespaces/default/services/lb-svc
  uid: e59b4a49-4d90-4bd8-a12a-a4a12e00cc4b
spec:
  clusterIP: 172.21.7.193
  externalTrafficPolicy: Cluster
  ports:
  - name: poc
    nodePort: 30178
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app.oam.dev/component: wordpress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 47.242.17.25
