apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: loadbalancer
  annotations:
    definition.oam.dev/description: "`LoadBalancer` is used to provider load balancer for applications and publish service."
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: loadbalancer.extend.oam.dev
  extension:
    template: |
      output: {
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            app: lb-svc
          name: lb-svc
          namespace: default
        spec:
          ports:
          - name: poc
            port: 8080
            protocol: TCP
            targetPort: 80
          selector:
            app.oam.dev/component: wordpress
          sessionAffinity: None
          type: LoadBalancer

      	apiVersion: "extend.oam.dev/v1alpha1"
      	kind:       "LoadBalancer"
      	spec: {
      		host: parameter.domain

      		if parameter.issuer != "" {
      			tls: {
      				issuerName: parameter.issuer
      			}
      		}

      		if parameter["rules"] != _|_ {
      			rules: parameter.rules
      		}
      	}
      }
      parameter: {
      	// +usage= Domain name
      	domain: *"" | string

      	issuer: *"" | string
      	rules?: [...{
      		path:          string
      		rewriteTarget: *"" | string
      	}]
      }
      
