apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 2
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: zzxwill/keda-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.1"
