apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaler-poc
  namespace: default
  labels:
    deploymentName: php-apache
spec:
  scaleTargetRef:
    deploymentName: php-apache
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cron
      metadata:
        # Required
        timezone: Asia/Shanghai # The acceptable values would be a value from the IANA Time Zone Database.
        start: 13 * * * *       # Every hour on the 30th minute
        end: 45 * * * *         # Every hour on the 45th minute
        desiredReplicas: "3"    # String.
