apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: deployments.apps
  annotations:
    oam.appengine.info/apiVersion: "apps/v1"
    oam.appengine.info/kind: "Deployment"
spec:
  definitionRef:
    name: deployments.apps
  extension:
    template: |
      output: {
      	apiVersion: "apps/v1"
      	kind:       "Deployment"
      	metadata: name: parameter.name
      	spec: {
      		containers: [{
      			image: parameter.image
      			name:  parameter.name
      			ports: [{
      				containerPort: parameter.port
      				protocol:      "TCP"
      				name:          "default"
      			}]
      		}]
      	}
      }

      #deployment: {
      	name:  string
      	image: string
      	port:  *8080 | int
      }
      parameter: #deployment