apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: default
spec:
  ports:
    - name: poc
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
  type: "LoadBalancer"

---

