apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: default
spec:
  ports:
    - name: poc
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: s1
  type: "LoadBalancer"

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: s1
  name: s1
  namespace: default
spec:
  containers:
    - image: wordpress:php7.4-apache
      imagePullPolicy: IfNotPresent
      name: s1
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 500m
