apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: loadbalancer
  annotations:
    definition.oam.dev/description: Provide loadbalancer for an application and publish its service"
spec:
  appliesToWorkloads:
    - webservice
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: service
  extension:
    template: |
      output: {
        apiVersion: "v1"
        kind: "Service"
        spec: {
          ports: parameter.ports
          selector: {
            "app.oam.dev/component": context.name
          }
          type: "LoadBalancer"
        }
      }

      parameter: {
      	ports: [...{
            name: string
            port: *80 | int
            protocol: *"TCP" | string
            targetPort: int
      	}]
      }
